Create registration form
wojbog/praktyki_frontend pull request #5
Opened 2021-05-06 09:31 UTC by shhhQuiettt

Add RegisterForm component
HTML CSS
Validation funtions in validation.js

2021-05-06 11:09 UTC, wojbog commented on src/components/RegisterForm.js
> +                console.log("dup")
niepotrzebny log

2021-05-06 11:09 UTC, wojbog reviewed
(jako niedoświadczony) wydaję mi się że jest ok

2021-05-06 11:27 UTC, shhhQuiettt commented on src/components/RegisterForm.js
> +            axios.post("https://localhost:3001/registration",
Trzeba zmienić na /newUser bo tak jest na serwerze, albo zmienić  na serwerze

2021-05-06 11:33 UTC, akruszewski requested changes

2021-05-06 11:33 UTC, akruszewski commented on src/components/RegisterForm.js
> +                console.log("dup")
Do repo wypychamy tylko produkcyjny kod. To nie wyglada na taki, do usuniecia.

2021-05-06 11:33 UTC, akruszewski commented on src/components/RegisterForm.js
> +        "name": "Adam",
Wciecie jest off.

2021-05-06 11:33 UTC, akruszewski commented on src/components/RegisterForm.js
> +    const [user, setUser] = useState({
State should be initialized empty.

2021-05-06 11:33 UTC, akruszewski commented on src/components/RegisterForm.js
> +            // console.log(user)
Nie wypychamy jako produkcyjnego kodu zakomentowanych lini.

2021-05-06 11:33 UTC, akruszewski commented on src/components/RegisterForm.js
> +                    invalid.style.backgroundColor = "#ff9999"
Lepiej byloby to zrobic jako warunkowe wyswietlenie komponentu.

2021-05-06 11:33 UTC, akruszewski commented on src/components/RegisterForm.js
> +            axios.post("https://localhost:3001/registration",
Host aplikacji powinien byc zmienna, wtedy latwiej bedzie go zmienic.

2021-05-06 11:33 UTC, akruszewski commented on src/components/RegisterForm.js
> +            axios.post("https://localhost:3001/registration",
Komunikacje z api najlepiej zrobic w osobnym module serwisowym, np service.js, a pozniej, kiedy zrobi sie wiecej kodu podzielic je na osobne pliki, w zaleznosci od domeny, np. user, field, itp.

2021-05-06 11:33 UTC, akruszewski commented on src/validation.js
> + export function validate(usr) { //returns array of invalid keys
Najlepiej validatory umiescic w serwisie.

2021-05-06 11:33 UTC, wojbog commented on src/components/RegisterForm.js
> +            {passDiff && <p className="invalid">Hasła się nie zgadzają!</p>}
komunikat nie znika gdy poprawi się pole pass zamiast pass-confirmation, dodać sprawdzanie do pass

2021-05-06 11:50 UTC, akruszewski commented on src/components/RegisterForm.js
> +            axios.post("https://localhost:3001/registration",
proponuje `createUser`, endpointy najlepiej jako nazwy akcji ktore wykonuja.

2021-05-10 08:00 UTC, akruszewski requested changes

2021-05-10 08:00 UTC, akruszewski commented on src/service.js
> +export function validate(usr) { //returns array of invalid keys
Nazwalbym to validateUser, zeby bylo wiadomo co to wlasciwie waliduje + jakas dokumentacja by sie przydala.

2021-05-10 08:00 UTC, akruszewski commented on src/service.js
> +export function createUser(user) {
Tutaj tez potrzebna jest dokumentacja funkcji.

2021-05-10 08:00 UTC, akruszewski commented on src/components/RegisterForm.js
> +            {invalid && <p className="invalid">Jedno lub więcej pól jest nieprawidłowych!</p>}
To jest za mało jezeli chodzi o user expirience. Kazde pole powinno miec info walidacyjne, co konkretnie jest nie tak.

2021-05-11 11:12 UTC, akruszewski approved these changes

2021-05-11 12:35 UTC, merged