Add LoginForm
wojbog/praktyki_frontend pull request #6
Opened 2021-05-14 06:36 UTC by shhhQuiettt

Login form added
LoginForm test added
Protected route added
Code is formated now
Basic route added

2021-05-14 09:51 UTC, GarrusNapp requested changes

2021-05-14 09:51 UTC, GarrusNapp commented on src/components/LoginForm.js
> +        if (user.email == "" || user.pass == "") {
Widziałem, że macie potworzone funkcje walidacyjne. 
Niech one obsłużą puste hasła / emaile, tak, żeby cała walidacja odbywała się tam, a nie częściowo w tym komponencie.

2021-05-14 09:51 UTC, GarrusNapp commented on src/components/LoginForm.js
> +            if (user.pass === "") {
Ogólnie co do if, korzystajcie z tego że niektóre wartości są truthy/falsy np. `if (!user.pass)` zamiast `if (user.pass === "")`
Przy większej ilości ifów zwiększa to czytelność.

2021-05-14 09:51 UTC, GarrusNapp commented on src/components/Input.js
> +                            setIsValid({ ...isValid, [id]: true })
`[id]` to to samo co [`${id}`]

2021-05-14 09:51 UTC, GarrusNapp commented on src/components/LoginForm.js
> +    const [user, setUser] = useState({
Zamiast dwóch state `user` i `isValid` zrobiłbym 4 dla każdego pola. Będzie wtedy można pozbyć się obsługiwania `id` w inpucie, co uprości kod. 

Podobnie można uprościć obsługę errorów i zamiast używać booleanu valid, to dać array z errorami i w zależności czy jest pusty czy nie dodawać odpowiednie klasy i message.

2021-05-14 09:51 UTC, GarrusNapp commented on src/components/LoginForm.js
> +                    case "incorret password or email": {
*incorrect

2021-05-14 09:51 UTC, GarrusNapp commented on src/components/Input.js
> +                    onChange == undefined
jak nie przyszedł prop onChange to nie robiłbym domyślnie żeby obsługiwał setUser, bo nie będzie się dało użyć gdzie indziej inputu.

2021-05-14 09:51 UTC, GarrusNapp commented on src/service.js
> +                isAuthenticated = true;
authenticated = true*

2021-05-14 09:51 UTC, GarrusNapp commented on src/service.js
> +                    /^[a-z\u00AA\u00B5\u00BA\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02C1\u02C6-\u02D1\u02E0-\u02E4\u02EC\u02EE\u0370-\u0374\u0376\u0377\u037A-\u037D\u037F\u0386\u0388-\u038A\u038C\u038E-\u
co to za szalony pattern?

2021-05-14 09:51 UTC, GarrusNapp commented on src/App.js
> +        <>
Można też zrobić też standardowego switcha, tego typu:
```
        <Switch>
          <Route path="/about">
            <About />
          </Route>
          <Route path="/users">
            <Users />
          </Route>
          <Route path="/">
            <Home />
          </Route>
        </Switch>
```
funkcje createUser / login mogą być importowane już w komponentach, które ich używają.

2021-05-14 09:51 UTC, GarrusNapp commented on src/components/Input.js
> +                value={value === undefined ? user[`${id}`] : value}
value bym zawsze raczej używał tego z propsów, a nie wysyłał usera w propsach wcale.

2021-05-18 09:03 UTC, akruszewski approved these changes

2021-05-19 09:11 UTC, GarrusNapp approved these changes

2021-05-24 08:17 UTC, merged